config/routes.rb
Rails.application.routes.draw do
  
  root "homes#top"
  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }#各モデルのコントローラを個別に指定できるように変更
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
  }#各モデルのコントローラを個別に指定できるように変更
  resources :users do
  	resources :time_cards
  end
  resources :admins
  

  namespace :admin do
  	root "homes#top"
    resources :admins
  end

  namespace :user do
  	root "homes#top"
  end
end

app/models/time_card.rb
class TimeCard < ApplicationRecord
	belongs_to :user

  class << self
	 # 今日のタイムカードを取得する
    def today(user)
      date = Date.today
      condition = { user: user, year: date.year, month: date.month, day: date.day }
      self.find_by(condition) || self.new(condition)
    end
     # 指定年月のタイムカードを取得する
    def monthly(user, year, month)
      self.where(user: user, year: year, month: month).order(:day).all
    end
  end
  
  # 勤務状況を取得する
  def working_status
    case [!!in_at, !!out_at]
    when [false, false]
      :未出社 # 未出社
    when [true, false]
      :勤務中 # 勤務中
    when [true, true]
      :退社済み # 退社済
    end
  end

  # タイムカードの日付を返す
  def date
    Date.new(year, month, day)
  end

  # 勤務時間を返す（単位は秒）
  def work_hours_in_seconds
    if in_at && out_at
      out_at - in_at
    else
      0
    end
  end
  
  
  private

    # カスタムバリデーション（正しい日付か？）
    def valid_date
      return if errors[:year].any? || errors[:month].any? || errors[:day].any?
      
      if !Date.valid_date?(year, month, day)
        errors[:base] << '不正な日付です'
      end
    end

    # カスタムバリデーション（退社時間が出社時間より後か？）
    def out_at_is_later_than_in_at
      return if in_at.nil? || out_at.nil?

      if in_at > out_at
        errors[:base] << '退社時間は、出社時間より後の時間である必要があります'
      end
    end
end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController
	
	
	def index
		@user = current_user
	    today = Date.today
	    @year = today.year
	    @month = today.month
	    @time_cards = monthly_time_cards(current_user, @year, @month)
	    @time_card = TimeCard.today(current_user)
	    @times = @user.time_cards
	  end

	  def show
	  	@user = current_user
	    @time_card = TimeCard.today(current_user)
	  end

	  def create
	    @time_card = TimeCard.today(current_user)
	    
	    if params[:in]
	      @time_card.in_at = Time.now
	    elsif params[:out]
	      @time_card.out_at = Time.now
	    end

	    if @time_card.save
	       redirect_to user_path(current_user)
	    else
	       root_path
	    end
	  end

	  private

	    # 指定年月の全ての日のタイムカードの配列を取得する（タイムカードが存在しない日はnil）
	    def monthly_time_cards(user, year, month)
	      number_of_days_in_month = Date.new(year, month, 1).next_month.prev_day.day
	      results = Array.new(number_of_days_in_month) # 月の日数分nilで埋めた配列を用意
	      time_cards = TimeCard.monthly(user, year, month)
	      time_cards.each do |card|
	        results[card.day - 1] = card
	      end
	      results
	    end

end

app/helpers/time_cards_helper.rb
module TimeCardsHelper
end

app/views/time_cards/index.html.erb
<h1>タイムカード一覧画面<%= @year %>年<%= @month %>月度勤務一覧</h1>
  <table class="table, table-bordered, table-condensed">
  	<thead>
  		<tr>
  			<th>日付</th>
  			<th>曜</th>
  			<th>出社時間</th>
  			<th>退社時間</th>
  			<th>勤務時間</th>
  		</tr>
  	</thead>
  <% @times.each do |date| %>
  	<tbody>
  		<tr>
  			<td><%= date.date.day %></td>
  			<td></td>
        <% if date.blank? %>
  			<td></td>
  			<td></td>
  			<td></td>
        <% else %>
  			<td><%= date.in_at %></td>
  			<td><%= date.out_at %></td>
  			<td><%= date.work_hours_in_seconds%></td>
  	    <%end%>
  		</tr>
  	</tbody>
  <% end %>
  </table>

app/views/time_cards/show.html.erb
<h1>タイムカード打刻画面</h1>
<div class='row'>
  <div class='col-xs-6'>
  	<p>今日は <%= Date.today %>です。</p>
  	<p></p>
  </div>
</div>
<p>現在状況</p>
<%= @time_card.working_status %>
<%= form_tag(user_time_cards_path, method: :post) do %> 
  <%= submit_tag('出社', name: 'in', id: 'in', disabled: !!@time_card.in_at, class: 'btn btn-default')%>
  <%= submit_tag('退社', name: 'out', id: 'out', disabled: !@time_card.in_at || !!@time_card.out_at, class: 'btn btn-default')%> 
<% end %>
<div>
	<%= button_to '勤務表確認', user_time_cards_path, method: :get, class: 'btn btn-default'%>
</div>